### ISSUE TITLE
Project-wide Settings

### ISSUE THREAD

**Issue by StevenXL** [pbrisbin/indirect#2]
Cool idea, but I wonder if having the configuration file at `~/.config/indirect/indirect.toml` kinda moves the problem around. 

Ideally, we'd be able to read the configuration at a `git-repo` level, so that we could:

1. Commit that file into the repository and ensure anyone with the `indirect` binary uses the same `fourmolu` and
2. Have different `fourmolu`s depending on repo. 

Having `indirect` do a lookup for config files, starting with the directory in which it is called, and then moving up. I think this might require it to also keep the binaries indexed by version. 

~~Conceptually, a map from `Map InvokingDir Config`.~~

~~Map.fromList [(MegaRepo, IndirectConfig), (OtherRepo, IndirectConfig)]~~

**Comment by pbrisbin** [comment]
I think in order to solve the problem we need to support both. What we're dealing with is:

1. A project concern: when `fourmolu` is invoked for this project, it should be v0.13
2. A user concern: On my system, Fourmolu v0.13 lives at `~/.local/bin/fourmolu-0.13.0.1` and should be installed via `curl...`

Using a checked-in `.indirect.toml` really biffs it on (2). Now you need all users to have `curl` (fine), be OK with versioned things living in `~/.local/bin/name-version` (getting dicey), and work when installing the `-linux-x86_64` release artifact (deal breaker). Or you layer on additional complexity to be able to use (e.g.) `${arch}` and `${os}` in the `install` strings, etc, etc. I don't like that direction.

Given that, I think what the project is proposing at this stage is to address (2) in user-config (as it should and must be), and by the `.rules` feature, users can accomplish (1) without any extra implementation in `indirect` at all. A pretty good place to start.

Then, what we could do next is support merging configurations, and load `.indirect.toml` as an override of what's in config `~/.config`. Now, you can accomplish a setup like this:

```toml
# ~/.config/indirect/indirect.toml
[fourmolu]
vars.version = "0.16.0.1" # what I prefer on my own projects

binary = "${name}-${version}"
install = """
...
"""
```

```toml
# ~/code/some-project/.indirect.toml
[fourmolu]
vars.version = "0.13.0.1" # what this project needs
```

The implementation is pretty simple (it's `Semigroup`s all the way down), and boom, Bob's you're uncle.

WDYT?
